### ISSUE TITLE
Smtcoq_plugin  not found

### ISSUE THREAD

**Issue by acorrenson** [smtcoq/smtcoq-api#1]
After installing ocaml 4.10 in a local switch and installing smtcoq 2.0+8.11 (in the same local switch),
I still can't compile smtcoq API. `make` return the following message :

```
coq_makefile -f _CoqProject -o Makefile
CAMLOPT -c -for-pack Smtcoq_api_plugin api.ml
File "api.ml", line 13, characters 11-24:
13 | module S = Smtcoq_plugin
                ^^^^^^^^^^^^^
Error: Unbound module Smtcoq_plugin
make[1]: *** [api.cmx] Error 2
make: *** [all] Error 2
```

**Comment by ckeller** [comment]
I started a port for Coq-8.13 in [this branch](https://github.com/smtcoq/smtcoq-api/tree/coq-8.13). It does not compile yet but I will try to finish it as quickly as possible.

**Comment by ckeller** [comment]
The port was actually easy :-) The branch `coq-8.13` is now the default branch, and the branch `coq-8.11` will not be maintained.

**Comment by acorrenson** [comment]
Wow that was fast... Thanks a lot @ckeller  ! the problem seems to be solved ^^
